module:
  admin_toolbar: 0
  block: 0
  breakpoint: 0
  color: 0
  dblog: 0
  dynamic_page_cache: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  language: 0
  link: 0
  locale: 0
  menu_link_content: 0
  menu_ui: 0
  module_filter: 0
  node: 0
  page_cache: 0
  system: 0
  text: 0
  toolbar: 0
  update: 0
  user: 0
  minimal: 1000
theme:
  stark: 0
  bootstrap: 0
  fixmy: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
langcode: de
profile: minimal
